name: String Greater Than Action Test

on: 
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Old version greater than new version
    steps:
      - name: Check Version
        uses: francis94c/string-greater-than-action@master
        with:
          string1: v2.4.5+80
          string2: v1.2.3+40
          failOnLesser: true
          failOnEqual: true